// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using leanExtraWebApp.Data;

#nullable disable

namespace leanExtraWebApp.Migrations
{
    [DbContext(typeof(ServerManagmentContext))]
    [Migration("20250117092201_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("leanExtraWebApp.Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerId");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            City = "Toronto",
                            IsOnline = true,
                            Name = "Server1"
                        },
                        new
                        {
                            ServerId = 2,
                            City = "Toronto",
                            IsOnline = true,
                            Name = "Server2"
                        },
                        new
                        {
                            ServerId = 3,
                            City = "Toronto",
                            IsOnline = true,
                            Name = "Server3"
                        },
                        new
                        {
                            ServerId = 4,
                            City = "Montreal",
                            IsOnline = true,
                            Name = "Server4"
                        },
                        new
                        {
                            ServerId = 5,
                            City = "Montreal",
                            IsOnline = true,
                            Name = "Server5"
                        },
                        new
                        {
                            ServerId = 6,
                            City = "Ottawa",
                            IsOnline = true,
                            Name = "Server6"
                        },
                        new
                        {
                            ServerId = 7,
                            City = "Ottawa",
                            IsOnline = true,
                            Name = "Server7"
                        },
                        new
                        {
                            ServerId = 8,
                            City = "Calgary",
                            IsOnline = true,
                            Name = "Server8"
                        },
                        new
                        {
                            ServerId = 9,
                            City = "Calgary",
                            IsOnline = false,
                            Name = "Server9"
                        },
                        new
                        {
                            ServerId = 10,
                            City = "Halifax",
                            IsOnline = false,
                            Name = "Server10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
